### ISSUE TITLE
Issue with builds 3.6.1, 3.6.2 on Jitpack

### ISSUE THREAD

**Issue by trez00d** [null321-jared/rollbackcore#2]
Seems like builds 3.6.1 and 3.6.2 on Jitpack have a build error, preventing the use of maven to use the api. 3.6.0-BETA works but has some issues importing dependencies.  
![Screenshot from 2024-03-28 17-41-03](https://github.com/null321-jared/rollbackcore/assets/160378609/cde8bd11-1a60-4f19-8eed-93d83fa74814)

**Comment by null321-jared** [comment]
Thank you for bringing this to my attention. It appears that Jitpack defaults to Java 8 unless otherwise specified, and 3.6.1 upgraded it to Java 17.

In `3.6.3` I set the java version, so it should work now.

Let me know if you have any other issues.
